spring:
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.liang.pojo


#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

comment.avatar: /images/avatar.png